name: Stock Scanner

on:
  workflow_dispatch:

  schedule:
    - cron: "10 6 * * 1-5"   # 06:10 UTC (Mon-Fri)

jobs:
  scan:
    runs-on: ubuntu-latest

    env:
      EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install
        run: |
          pip install -r requirements.txt

      - name: Run Scanner
        run: |
          python app.py

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: stock-signals
          path: output
